spring.application.name=character-tracker-app

spring.datasource.url=${DB_URL:jdbc:mysql://zephyr.proxy.rlwy.net:38293/railway}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false