/**
 * Entity class representing a race record
 * stored in the races database table.
 * 
 * This class contains race-related data
 * used throughout the application.
 * 
 * @author Daniel Louise
 * @version 1.0
 * 
 */
package com.gcu.charactertracker.entities;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


@Entity
@Table(name = "classes")
public class ClassEntity
{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "class_id")
    private Integer classId;

    @Column(name = "class_name", nullable = false, unique = true)
    private String className;

    @Column(name = "class_type")
    private String classType;

    @Column(name = "class_description")
    private String classDescription;

    @Column(name = "added_at")
    private LocalDateTime addedAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Default constructor for ClassEntity, required by JPA. Initializes a new instance of the ClassEntity class without setting any fields.
     */
    public ClassEntity()
    {
    }

    /**
     * Gets the unique identifier of the class. This ID is automatically generated by the database when a new class is added.
     * @return the classId of the ClassEntity
     */
    public Integer getClassId()
    {
        return classId;
    }

    /**
     * Sets the unique identifier of the class. This method is typically not used directly, as the classId is generated by the database, but it can be used for testing or when manually setting IDs.
     * @param classId the classId to set for the ClassEntity
     */
    public void setClassId(Integer classId)
    {
        this.classId = classId;
    }

    /**
     * Gets the name of the class. The class name is a required field and must be unique across all classes in the database.
     * @return the className of the ClassEntity
     */
    public String getClassName()
    {
        return className;
    }

    /**
     * Sets the name of the class. The class name is a required field and must be unique across all classes in the database. If a duplicate class name is provided, it will result in a database constraint violation.
     * @param className the className to set for the ClassEntity
     */
    public void setClassName(String className)
    {
        this.className = className;
    }

    /**
     * Gets the type of the class. The class type is an optional field that can be used to categorize classes into different groups or archetypes, such as "Warrior", "Mage", "Rogue", etc.
     * @return the classType of the ClassEntity, which can be used to categorize classes into different groups or archetypes
     */
    public String getClassType()
    {
        return classType;
    }

    /**
     * Sets the type of the class. The class type is an optional field that can be used to categorize classes into different groups or archetypes, such as "Warrior", "Mage", "Rogue", etc.
     * @param classType the classType to set for the ClassEntity, which can be used to categorize classes into different groups or archetypes
     */
    public void setClassType(String classType)
    {
        this.classType = classType;
    }

    /**
     * Gets the description of the class. The class description is an optional field that can provide additional information about the class, such as its abilities, role in the game, or any other relevant details.
     * @return the classDescription of the ClassEntity, which can provide additional information about the class such as its abilities or role in the game
     */
    public String getClassDescription()
    {
        return classDescription;
    }

    /**
     * Sets the description of the class. The class description is an optional field that can provide additional information about the class, such as its abilities, role in the game, or any other relevant details.
     * @param classDescription  the classDescription to set for the ClassEntity, which can provide additional information about the class such as its abilities or role in the game
     */
    public void setClassDescription(String classDescription)
    {
        this.classDescription = classDescription;
    }

    /**
     * Gets the timestamp for when the class was added to the database. This field is typically set to the current date and time when a new class is created and saved to the database.
     * @return the addedAt timestamp of the ClassEntity, which indicates when the class was first added to the database
     */
    public LocalDateTime getAddedAt()
    {
        return addedAt;
    }

    /**
     * Sets the timestamp for when the class was added to the database. This field is typically set to the current date and time when a new class is created and saved to the database.
     * @param addedAt the addedAt timestamp to set for the ClassEntity, typically set to the current date and time when the class is created
     */
    public void setAddedAt(LocalDateTime addedAt)
    {
        this.addedAt = addedAt;
    }

    /**
     * Gets the timestamp for when the class was last updated. This field should be updated whenever any changes are made to the class information
     * @return the updatedAt timestamp of the ClassEntity, which indicates the last time the class information was modified
     */
    public LocalDateTime getUpdatedAt()
    {
        return updatedAt;
    }

    /**
     * Sets the timestamp for when the class was last updated. This field should be updated whenever any changes are made to the class information
     * @param updatedAt the updatedAt timestamp to set for the ClassEntity, typically set to the current date and time when the class is modified
     */
    public void setUpdatedAt(LocalDateTime updatedAt)
    {
        this.updatedAt = updatedAt;
    }
}